import type { Metadata, Viewport } from "next";
import "./globals.css";
import BottomNav from "@/components/BottomNav";
import ServiceWorkerRegistrar from "@/components/ServiceWorkerRegistrar";

export const metadata: Metadata = {
  title: "Daily Grace",
  description: "One encouraging word. One verse. One small action. Every day.",
  // apple-touch-icon and manifest are auto-generated by Next.js from:
  //   app/apple-icon.tsx  →  <link rel="apple-touch-icon">
  //   app/manifest.ts     →  <link rel="manifest">
  other: {
    // Enable standalone (full-screen) mode when added to iPhone Home Screen
    "apple-mobile-web-app-capable": "yes",
    // Status bar style in standalone mode:
    // "default" = system default (cream/light bar matches our bg color)
    "apple-mobile-web-app-status-bar-style": "default",
    // The name shown under the icon on the Home Screen
    "apple-mobile-web-app-title": "Daily Grace",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Prevent accidental zoom on iOS — the card is designed for a fixed layout
  maximumScale: 1,
  userScalable: false,
  // Matches the cream background in the iOS status bar area
  themeColor: "#FAF7F2",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-grace-cream antialiased overscroll-none min-h-dvh">
        {/*
          pb accounts for: BottomNav height (~60px) + bottom safe area.
          Using calc() so it adapts to devices with/without a home indicator.
        */}
        <main className="pb-[calc(4rem+env(safe-area-inset-bottom))]">
          {children}
        </main>

        <BottomNav />
        <ServiceWorkerRegistrar />
      </body>
    </html>
  );
}
